name: Run Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv and enable cache (modern package manager)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      
      - name: Install dependencies from pyproject.toml
        run: uv sync

      - name: Set OPENAI_API_KEY from secret
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run tests
        run: uv run pytest