name: Run Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv (modern package manager)
        run: |
          pip install uv
      
      - name: Install dependencies from pyproject.toml
        run: |
          uv pip install --system
      
      - name: Cache uv (improves build time by caching)
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}

      - name: Run tests
        run: |
          pytest tests/